src/helfertool/urls.py
from django.conf import settings
from django.urls import include, path, register_converter
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.defaults import page_not_found, server_error, permission_denied, bad_request
from django.views.generic import TemplateView

from .converters import DateConverter

register_converter(DateConverter, "date")

urlpatterns = [
    # django admin interface
    path("manage/django/", admin.site.urls),
    # internationalization
    path("i18n/", include("django.conf.urls.i18n")),
    # django-select2
    path("select2/", include("django_select2.urls")),
    # django-simple-captcha
    path("captcha/", include("captcha.urls")),
    # authentication
    path("login/", auth_views.LoginView.as_view(template_name="helfertool/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    # apps without event name in url
    path("manage/settings/", include("toolsettings.urls")),
    path("manage/account/", include("account.urls")),
]

# add oidc urls if enabled
if settings.OIDC_CUSTOM_PROVIDER_NAME is not None:
    urlpatterns += [
        path("oidc/", include("mozilla_django_oidc.urls")),
        path(
            "oidc/failed",
            TemplateView.as_view(template_name="helfertool/login_oidc_failed.html"),
            name="oidc_failed",
        ),
    ]

# this is placed at the end to prevent that event names overwrite other urls
urlpatterns += [
    path("", include("help.urls")),
    path("", include("news.urls")),
    path("", include("registration.urls")),
    path("", include("statistic.urls")),
    path("", include("badges.urls")),
    path("", include("gifts.urls")),
    path("", include("inventory.urls")),
    path("", include("mail.urls")),
    path("", include("prerequisites.urls")),
    path("", include("toollog.urls")),
    path("", include("adminautomation.urls")),
]

# for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL + "public", document_root=settings.MEDIA_ROOT / "public")

    urlpatterns += [
        path("errors/400/", bad_request, {"exception": None}),
        path("errors/403/", permission_denied, {"exception": None}),
        path("errors/404/", page_not_found, {"exception": None}),
        path("errors/500/", server_error),
        path(
            "errors/banned/",
            TemplateView.as_view(template_name="helfertool/login_banned.html"),
        ),
    ]

src/help/urls.py
from django.urls import path

from . import views

app_name = "help"
urlpatterns = [
    path("help/", views.create_issue, name="create_issue"),
]

src/inventory/urls.py
from django.urls import path

from . import views

app_name = "inventory"
urlpatterns = [
    # pages for single event
    path("<slug:event_url_name>/inventory/settings/", views.event_settings, name="event_settings"),
    path("<slug:event_url_name>/inventory/register/", views.register_item, name="register"),
    path(
        "<slug:event_url_name>/inventory/register/<int:item_pk>/",
        views.register_badge,
        name="register_badge",
    ),
    path("<slug:event_url_name>/inventory/take_back/", views.take_back_item, name="take_back"),
    path(
        "<slug:event_url_name>/inventory/take_back/<int:item_pk>/",
        views.take_back_badge,
        name="take_back_badge",
    ),
    path(
        "<slug:event_url_name>/inventory/take_back/<int:item_pk>/direct/",
        views.take_back_direct,
        name="take_back_direct",
    ),
    path("<slug:event_url_name>/inventory/list/", views.event_list, name="list"),
    # inventory management
    path("manage/inventory/", views.inventory_list, name="inventory_list"),
    path("manage/inventory/new/", views.edit_inventory, name="new_inventory"),
    path("manage/inventory/<int:inventory_pk>/", views.edit_inventory, name="edit_inventory"),
    path("manage/inventory/<int:inventory_pk>/delete", views.delete_inventory, name="delete_inventory"),
    path("manage/inventory/<int:inventory_pk>/items/", views.inventory_items, name="inventory_items"),
    # item management
    path("manage/inventory/<int:inventory_pk>/items/new/", views.edit_item, name="new_item"),
    path(
        "manage/inventory/<int:inventory_pk>/items/<int:item_pk>/",
        views.edit_item,
        name="edit_item",
    ),
    path(
        "manage/inventory/<int:inventory_pk>/items/<int:item_pk>/delete/",
        views.delete_item,
        name="delete_item",
    ),
]

src/gifts/views/list.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.cache import never_cache

from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event, Helper
from registration.permissions import has_access, ACCESS_GIFTS_EDIT, ACCESS_GIFTS_VIEW_SUMMARY

from ..forms import GiftSettingsForm
from ..models import Gift, GiftSet
from .utils import notactive

from collections import OrderedDict

import logging

logger = logging.getLogger("helfertool.gifts")


@login_required
@never_cache
def list(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_GIFTS_EDIT):
        return nopermission(request)

    # check if active
    if not event.gifts:
        return notactive(request)

    # manage gift settings
    settings_form = GiftSettingsForm(request.POST or None, instance=event.giftsettings)

    if settings_form.is_valid():
        settings_form.save()

        log_msg = "giftsettings changed"
        logger.info(
            log_msg,
            extra={
                "user": request.user,
                "event": event,
            },
        )

        return redirect("gifts:list", event_url_name=event.url_name)

    # grab gifts and giftsets
    gifts = Gift.objects.filter(event=event)
    gift_sets = GiftSet.objects.filter(event=event)

    context = {"event": event, "gifts": gifts, "gift_sets": gift_sets, "settings_form": settings_form}
    return render(request, "gifts/list.html", context)


@login_required
@never_cache
@archived_not_available
def list_deposit(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_GIFTS_VIEW_SUMMARY):
        return nopermission(request)

    # check if active
    if not event.gifts:
        return notactive(request)

    helpers = event.helper_set.filter(gifts__deposit__isnull=False, gifts__deposit_returned=False)

    if helpers:
        deposit_sum = helpers.aggregate(total=Sum("gifts__deposit"))["total"]
    else:
        deposit_sum = None

    context = {"event": event, "helpers": helpers, "deposit_sum": deposit_sum}
    return render(request, "gifts/list_deposit.html", context)


@login_required
@never_cache
@archived_not_available
def list_shirts(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_GIFTS_VIEW_SUMMARY):
        return nopermission(request)

    # check if active
    if not event.gifts:
        return notactive(request)

    if event.ask_shirt:
        helpers = event.helper_set.filter(gifts__buy_shirt=True)

        num_shirts = OrderedDict()
        shirts = helpers.values("shirt").annotate(num=Count("shirt"))
        for size, name in event.get_shirt_choices():
            num = 0

            try:
                num = shirts.get(shirt=size)["num"]
            except Helper.DoesNotExist:
                pass

            num_shirts.update({name: num})
    else:
        helpers = None
        num_shirts = None

    context = {"event": event, "helpers": helpers, "num_shirts": num_shirts, "shirts_not_active": not event.ask_shirt}
    return render(request, "gifts/list_shirts.html", context)

src/inventory/views/admin.py
from django.conf import settings
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.cache import never_cache

from ..decorators import any_inventory_admin_required, inventory_admin_required
from ..forms import InventoryForm, InventoryDeleteForm, ItemForm, ItemDeleteForm
from ..models import Inventory, Item


@any_inventory_admin_required
@never_cache
def inventory_list(request):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    inventories = Inventory.objects.all()

    context = {"inventories": inventories}
    return render(request, "inventory/admin/inventory_list.html", context)


@inventory_admin_required
@never_cache
def edit_inventory(request, inventory=None):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    # permission checking is done in inventory_admin_required
    form = InventoryForm(request.POST or None, instance=inventory)

    if form.is_valid():
        form.save()
        return redirect("inventory:inventory_list")

    # render page
    context = {"form": form}
    return render(request, "inventory/admin/edit_inventory.html", context)


@inventory_admin_required
@never_cache
def delete_inventory(request, inventory):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    # permission checking is done in inventory_admin_required
    form = InventoryDeleteForm(request.POST or None, instance=inventory)

    if form.is_valid():
        form.delete()
        return redirect("inventory:inventory_list")

    # render page
    context = {"inventory": inventory, "form": form}
    return render(request, "inventory/admin/delete_inventory.html", context)


@inventory_admin_required
@never_cache
def inventory_items(request, inventory):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    # permission checking is done in inventory_admin_required
    context = {"inventory": inventory, "items": inventory.item_set.all()}
    return render(request, "inventory/admin/inventory_items.html", context)


@inventory_admin_required
@never_cache
def edit_item(request, inventory, item_pk=None):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    item = None
    if item_pk:
        item = get_object_or_404(Item, pk=item_pk)

        if item.inventory != inventory:
            raise Http404()

    form = ItemForm(request.POST or None, instance=item, inventory=inventory)

    if form.is_valid():
        # TODO: handle unique_together constraint
        form.save()
        return redirect("inventory:inventory_items", inventory_pk=inventory.pk)

    context = {"form": form}
    return render(request, "inventory/admin/edit_item.html", context)


@inventory_admin_required
@never_cache
def delete_item(request, inventory, item_pk):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    item = get_object_or_404(Item, pk=item_pk)

    if item.inventory != inventory:
        raise Http404()

    form = ItemDeleteForm(request.POST or None, instance=item)

    if form.is_valid():
        form.delete()
        return redirect("inventory:inventory_items", inventory_pk=inventory.pk)

    # render page
    context = {"item": item, "form": form}
    return render(request, "inventory/admin/delete_item.html", context)

src/inventory/views/event_list.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import never_cache

from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event
from registration.permissions import has_access, ACCESS_INVENTORY_HANDLE

from ..models import UsedItem
from .utils import notactive


@login_required
@never_cache
@archived_not_available
def event_list(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    used_items = UsedItem.objects.filter(helper__event=event)

    context = {"event": event, "used_items": used_items}
    return render(request, "inventory/list.html", context)

src/inventory/views/register.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import never_cache

from badges.forms import BadgeBarcodeForm
from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event, Helper
from registration.permissions import has_access, ACCESS_INVENTORY_HANDLE

from ..exceptions import AlreadyAssigned
from ..forms import InventoryBarcodeForm
from ..models import Item, UsedItem
from .utils import notactive


@login_required
@never_cache
@archived_not_available
def register_item(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    # data from last registration
    last_helper_pk = request.session.pop("inventory_helper_pk", None)
    last_item_name = request.session.pop("inventory_item_name", None)
    try:
        last_helper = Helper.objects.get(pk=last_helper_pk)
        last_helper_items = UsedItem.objects.filter(helper=last_helper, timestamp_returned=None)
    except Helper.DoesNotExist:
        last_helper = None
        last_helper_items = None

    # form for new registration
    form = InventoryBarcodeForm(request.POST or None, event=event)

    not_available = False
    if form.is_valid():
        if form.item.is_available(event):
            return redirect("inventory:register_badge", event_url_name, form.item.pk)
        else:
            not_available = True

    context = {
        "event": event,
        "form": form,
        "not_available": not_available,
        "last_helper": last_helper,
        "last_helper_items": last_helper_items,
        "last_item_name": last_item_name,
    }
    return render(request, "inventory/register_item.html", context)


@login_required
@never_cache
@archived_not_available
def register_badge(request, event_url_name, item_pk):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    already_assigned = False
    special_badge = False
    try:
        item = Item.objects.get(pk=item_pk)

        form = BadgeBarcodeForm(request.POST or None, event=event)

        if form.is_valid():
            # it is a valid badge
            if form.badge.helper:
                # normal badge with helper -> do it
                item.add_to_helper(form.badge.helper)

                # update saved data in session
                request.session["inventory_helper_pk"] = str(form.badge.helper.pk)
                request.session["inventory_item_name"] = item.name

                return redirect("inventory:register", event_url_name)
            else:
                # no helper -> special badge
                special_badge = True
    except (KeyError, Item.DoesNotExist):
        form = None
    except AlreadyAssigned:
        already_assigned = True

    context = {"event": event, "form": form, "already_assigned": already_assigned, "special_badge": special_badge}
    return render(request, "inventory/register_badge.html", context)

src/inventory/views/settings.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import never_cache

from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event
from registration.permissions import has_access, ACCESS_INVENTORY_EDIT

from ..forms import InventorySettingsForm
from .utils import notactive


@login_required
@never_cache
@archived_not_available
def event_settings(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_EDIT):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    form = InventorySettingsForm(request.POST or None, instance=event.inventory_settings)
    if form.is_valid():
        form.save()
        return redirect("inventory:event_settings", event_url_name)

    context = {"event": event, "form": form}
    return render(request, "inventory/event_settings.html", context)

src/inventory/views/utils.py
from django.shortcuts import render


def notactive(request):
    return render(request, "inventory/not_active.html")

src/inventory/templates/inventory/event_settings.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons %}

{% block content %}
    <h1>{% trans "Inventory settings" %}</h1>

    <form action="" method="post">
        {% csrf_token %}

        {% bootstrap_form form layout="floating" %}

        <button type="submit" class="btn btn-outline-primary">{% icon "save" %} {% trans "Save" %}</button>
    </form>
{% endblock %}

src/inventory/templates/inventory/list.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 inventory %}

{% block content %}
    <h1>{% trans "Inventory" %}</h1>

    {% if used_items %}
        {% regroup used_items by item as item_groups %} {# TODO: sort by item #}
        <ul class="list-group">
            {% for group in item_groups %}
            <li class="list-group-item mb-3">
                <div class="row">
                    <div class="col-12 col-md-4 py-1">
                        {{ group.grouper.name }}
                    </div>
                    <div class="col-12 col-md-8 py-1">
                        {% active_uses group.list as num_uses %}
                        {% if num_uses == 0 %}
                            {% trans "Not in use" %}
                        {% elif group.grouper.inventory.multiple_assignments %}
                            <span class="text-danger">
                                {% blocktrans trimmed %}
                                    {{ num_uses }} times in use
                                {% endblocktrans %}
                            </span>
                        {% else %}
                            <span class="text-danger">
                            {% with group.list|last as last %}
                                {% blocktrans trimmed with helper=last.helper%}
                                    In use: {{ helper }}
                                {% endblocktrans %}
                            {% endwith %}
                            </span>
                        {% endif %}

                        <br/>

                        <a data-bs-toggle="collapse" href="#log-{{ group.grouper.pk }}">
                            {% trans "Show log" %}
                        </a>

                        <div id="log-{{ group.grouper.pk }}" class="collapse">
                            <ul class="reset-list">
                                {% for use in group.list|dictsort:"timestamp" %}
                                    <li>
                                        {% if use.timestamp_returned %}
                                            {{ use.helper }}<br />
                                            <span class="text-muted">
                                                {{ use.timestamp|date:"SHORT_DATETIME_FORMAT" }}
                                                {% trans "to" %}
                                                {{ use.timestamp_returned|date:"SHORT_DATETIME_FORMAT" }}
                                            </span>
                                        {% else %}
                                            <span class="text-danger">
                                                <strong>{{ use.helper }}</strong><br/>
                                                {% trans "Since" %}
                                                {{ use.timestamp|date:"SHORT_DATETIME_FORMAT" }}
                                            </span>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="text-muted">{% trans "No items were given to helpers yet." %}</p>
    {% endif %}
{% endblock %}

src/inventory/templates/inventory/not_active.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <h1>{% trans "Inventory" %}</h1>

    <div class="alert alert-danger" role="alert">
        {% trans "The inventory functionality is not actived." %}
    </div>
{% endblock %}

src/inventory/templates/inventory/register_badge.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <h1>{% trans "Register: Scan badge" %}</h1>

    {% if not form %}
        <div class="alert alert-danger">
            {% trans "You have to scan the item first." %}
        </div>
        <a href="{% url 'inventory:register' event.url_name %}" class="btn btn-outline-primary">{% trans "Scan item" %}</a>
    {% else %}
        <form action="" method="post">
            {% csrf_token %}

            {% if already_assigned %}
                <div class="alert alert-danger">
                    {% trans "This item is already assigned to another helper." %}
                </div>
            {% endif %}

            {% if special_badge %}
            <div class="alert alert-danger">
                {% trans "This is a special badge, which is not associated with a helper. It cannot be used here." %}
            </div>
            {% endif %}

            {% bootstrap_form form show_label=False %}
        </form>

        <a href="{% url 'inventory:register' event.url_name %}" class="btn btn-outline-primary">{% trans "Scan other item" %}</a>
    {% endif %}
{% endblock %}

src/inventory/templates/inventory/register_item.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <h1>{% trans "Register: Scan item" %}</h1>

    <form action="" method="post">
        {% csrf_token %}

        {% if not_available %}
            <div class="alert alert-danger">
                {% trans "This item is already assigned to another helper." %}
            </div>
        {% endif %}

        {% bootstrap_form form show_label=False %}

        {% if not_available %}
            <a href="{% url 'inventory:take_back' event.url_name %}" class="btn btn-outline-danger">{% trans "Take item back" %}</a>
        {% endif %}
    </form>

    {% if last_helper and last_helper_items and last_item_name %}
        <div class="alert alert-info">
            <strong>{{ last_item_name }}</strong><br/>

            {% blocktrans trimmed with name as last_helper.full_name %}
                Assigned to {{ last_helper }}
            {% endblocktrans %}

            <br/><br/>

            {% trans "The helper now has these items:" %}
            <ul>
                {% for used_item in last_helper_items %}
                    <li>{{ used_item.item.name }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

src/inventory/templates/inventory/take_back_badge.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <h1>{% trans "Take back: Scan badge" %}</h1>

    {% if not form %}
        <div class="alert alert-danger">
            {% trans "You have to scan the item first." %}
        </div>
        <a href="{% url 'inventory:take_back' event.url_name %}" class="btn btn-outline-primary">{% trans "Scan item" %}</a>
    {% else %}
        <form action="" method="post">
            {% csrf_token %}

            {% if wrong_helper %}
                <div class="alert alert-danger">
                    {% trans "This item is not assigned to this helper, but to another helper." %}
                </div>
            {% endif %}

            {% bootstrap_form form show_label=False %}
        </form>

        <a href="{% url 'inventory:take_back' event.url_name %}" class="btn btn-outline-primary">{% trans "Scan other item" %}</a>

        {% if not item.inventory.multiple_assignments %}
            <a href="{% url 'inventory:take_back_direct' event.url_name item.pk %}" class="btn btn-outline-danger">{% trans "Take back without badge" %}</a>
        {% endif %}

    {% endif %}
{% endblock %}

src/inventory/templates/inventory/take_back_error.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <h1>{% trans "Error during taking back an item" %}</h1>

    <div class="alert alert-danger">
        {% if error == "multiple" %}
            {% trans "The item should only be assigned once, but multiple assignments are saved." %}
        {% elif error == "noassignment" %}
            {% trans "The item is not assigned to any helper." %}
        {% endif %}
    </div>
{% endblock %}

src/inventory/templates/inventory/take_back_item.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <h1>{% trans "Take back: Scan item" %}</h1>

    <form action="" method="post">
        {% csrf_token %}

        {% if not_in_use %}
            <div class="alert alert-danger">
                {% trans "This item is not in use." %}
            </div>
        {% endif %}

        {% bootstrap_form form show_label=False %}
    </form>

    {% if last_helper %}
        {% if last_helper_items %}
            <div class="alert alert-info">
                <strong>{{ last_helper.full_name }}</strong><br/>

            {% trans "The helper still has these items:" %}
            <ul>
                {% for used_item in last_helper_items %}
                    <li>{{ used_item.item.name }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="alert alert-success">
                <strong>{{ last_helper.full_name }}</strong><br/>

            {% trans "Everything returned!" %}
        {% endif %}

            </div>
    {% endif %}
{% endblock %}