src/helfertool/urls.py
from django.conf import settings
from django.urls import include, path, register_converter
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.defaults import page_not_found, server_error, permission_denied, bad_request
from django.views.generic import TemplateView

from .converters import DateConverter

register_converter(DateConverter, "date")

urlpatterns = [
    # django admin interface
    path("manage/django/", admin.site.urls),
    # internationalization
    path("i18n/", include("django.conf.urls.i18n")),
    # django-select2
    path("select2/", include("django_select2.urls")),
    # django-simple-captcha
    path("captcha/", include("captcha.urls")),
    # authentication
    path("login/", auth_views.LoginView.as_view(template_name="helfertool/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    # apps without event name in url
    path("manage/settings/", include("toolsettings.urls")),
    path("manage/account/", include("account.urls")),
]

# add oidc urls if enabled
if settings.OIDC_CUSTOM_PROVIDER_NAME is not None:
    urlpatterns += [
        path("oidc/", include("mozilla_django_oidc.urls")),
        path(
            "oidc/failed",
            TemplateView.as_view(template_name="helfertool/login_oidc_failed.html"),
            name="oidc_failed",
        ),
    ]

# this is placed at the end to prevent that event names overwrite other urls
urlpatterns += [
    path("", include("help.urls")),
    path("", include("news.urls")),
    path("", include("registration.urls")),
    path("", include("statistic.urls")),
    path("", include("badges.urls")),
    path("", include("gifts.urls")),
    path("", include("inventory.urls")),
    path("", include("mail.urls")),
    path("", include("prerequisites.urls")),
    path("", include("toollog.urls")),
    path("", include("adminautomation.urls")),
]

# for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL + "public", document_root=settings.MEDIA_ROOT / "public")

    urlpatterns += [
        path("errors/400/", bad_request, {"exception": None}),
        path("errors/403/", permission_denied, {"exception": None}),
        path("errors/404/", page_not_found, {"exception": None}),
        path("errors/500/", server_error),
        path(
            "errors/banned/",
            TemplateView.as_view(template_name="helfertool/login_banned.html"),
        ),
    ]

src/help/urls.py
from django.urls import path

from . import views

app_name = "help"
urlpatterns = [
    path("help/", views.create_issue, name="create_issue"),
]

src/inventory/urls.py
from django.urls import path

from . import views

app_name = "inventory"
urlpatterns = [
    # pages for single event
    path("<slug:event_url_name>/inventory/settings/", views.event_settings, name="event_settings"),
    path("<slug:event_url_name>/inventory/register/", views.register_item, name="register"),
    path(
        "<slug:event_url_name>/inventory/register/<int:item_pk>/",
        views.register_badge,
        name="register_badge",
    ),
    path("<slug:event_url_name>/inventory/take_back/", views.take_back_item, name="take_back"),
    path(
        "<slug:event_url_name>/inventory/take_back/<int:item_pk>/",
        views.take_back_badge,
        name="take_back_badge",
    ),
    path(
        "<slug:event_url_name>/inventory/take_back/<int:item_pk>/direct/",
        views.take_back_direct,
        name="take_back_direct",
    ),
    path("<slug:event_url_name>/inventory/list/", views.event_list, name="list"),
    # inventory management
    path("manage/inventory/", views.inventory_list, name="inventory_list"),
    path("manage/inventory/new/", views.edit_inventory, name="new_inventory"),
    path("manage/inventory/<int:inventory_pk>/", views.edit_inventory, name="edit_inventory"),
    path("manage/inventory/<int:inventory_pk>/delete", views.delete_inventory, name="delete_inventory"),
    path("manage/inventory/<int:inventory_pk>/items/", views.inventory_items, name="inventory_items"),
    # item management
    path("manage/inventory/<int:inventory_pk>/items/new/", views.edit_item, name="new_item"),
    path(
        "manage/inventory/<int:inventory_pk>/items/<int:item_pk>/",
        views.edit_item,
        name="edit_item",
    ),
    path(
        "manage/inventory/<int:inventory_pk>/items/<int:item_pk>/delete/",
        views.delete_item,
        name="delete_item",
    ),
]

src/inventory/views/admin.py
from django.conf import settings
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.cache import never_cache

from ..decorators import any_inventory_admin_required, inventory_admin_required
from ..forms import InventoryForm, InventoryDeleteForm, ItemForm, ItemDeleteForm
from ..models import Inventory, Item


@any_inventory_admin_required
@never_cache
def inventory_list(request):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    inventories = Inventory.objects.all()

    context = {"inventories": inventories}
    return render(request, "inventory/admin/inventory_list.html", context)


@inventory_admin_required
@never_cache
def edit_inventory(request, inventory=None):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    # permission checking is done in inventory_admin_required
    form = InventoryForm(request.POST or None, instance=inventory)

    if form.is_valid():
        form.save()
        return redirect("inventory:inventory_list")

    # render page
    context = {"form": form}
    return render(request, "inventory/admin/edit_inventory.html", context)


@inventory_admin_required
@never_cache
def delete_inventory(request, inventory):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    # permission checking is done in inventory_admin_required
    form = InventoryDeleteForm(request.POST or None, instance=inventory)

    if form.is_valid():
        form.delete()
        return redirect("inventory:inventory_list")

    # render page
    context = {"inventory": inventory, "form": form}
    return render(request, "inventory/admin/delete_inventory.html", context)


@inventory_admin_required
@never_cache
def inventory_items(request, inventory):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    # permission checking is done in inventory_admin_required
    context = {"inventory": inventory, "items": inventory.item_set.all()}
    return render(request, "inventory/admin/inventory_items.html", context)


@inventory_admin_required
@never_cache
def edit_item(request, inventory, item_pk=None):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    item = None
    if item_pk:
        item = get_object_or_404(Item, pk=item_pk)

        if item.inventory != inventory:
            raise Http404()

    form = ItemForm(request.POST or None, instance=item, inventory=inventory)

    if form.is_valid():
        # TODO: handle unique_together constraint
        form.save()
        return redirect("inventory:inventory_items", inventory_pk=inventory.pk)

    context = {"form": form}
    return render(request, "inventory/admin/edit_item.html", context)


@inventory_admin_required
@never_cache
def delete_item(request, inventory, item_pk):
    # check if feature is available
    if not settings.FEATURES_INVENTORY:
        raise Http404

    item = get_object_or_404(Item, pk=item_pk)

    if item.inventory != inventory:
        raise Http404()

    form = ItemDeleteForm(request.POST or None, instance=item)

    if form.is_valid():
        form.delete()
        return redirect("inventory:inventory_items", inventory_pk=inventory.pk)

    # render page
    context = {"item": item, "form": form}
    return render(request, "inventory/admin/delete_item.html", context)

src/inventory/views/event_list.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import never_cache

from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event
from registration.permissions import has_access, ACCESS_INVENTORY_HANDLE

from ..models import UsedItem
from .utils import notactive


@login_required
@never_cache
@archived_not_available
def event_list(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    used_items = UsedItem.objects.filter(helper__event=event)

    context = {"event": event, "used_items": used_items}
    return render(request, "inventory/list.html", context)

src/inventory/views/register.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import never_cache

from badges.forms import BadgeBarcodeForm
from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event, Helper
from registration.permissions import has_access, ACCESS_INVENTORY_HANDLE

from ..exceptions import AlreadyAssigned
from ..forms import InventoryBarcodeForm
from ..models import Item, UsedItem
from .utils import notactive


@login_required
@never_cache
@archived_not_available
def register_item(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    # data from last registration
    last_helper_pk = request.session.pop("inventory_helper_pk", None)
    last_item_name = request.session.pop("inventory_item_name", None)
    try:
        last_helper = Helper.objects.get(pk=last_helper_pk)
        last_helper_items = UsedItem.objects.filter(helper=last_helper, timestamp_returned=None)
    except Helper.DoesNotExist:
        last_helper = None
        last_helper_items = None

    # form for new registration
    form = InventoryBarcodeForm(request.POST or None, event=event)

    not_available = False
    if form.is_valid():
        if form.item.is_available(event):
            return redirect("inventory:register_badge", event_url_name, form.item.pk)
        else:
            not_available = True

    context = {
        "event": event,
        "form": form,
        "not_available": not_available,
        "last_helper": last_helper,
        "last_helper_items": last_helper_items,
        "last_item_name": last_item_name,
    }
    return render(request, "inventory/register_item.html", context)


@login_required
@never_cache
@archived_not_available
def register_badge(request, event_url_name, item_pk):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    already_assigned = False
    special_badge = False
    try:
        item = Item.objects.get(pk=item_pk)

        form = BadgeBarcodeForm(request.POST or None, event=event)

        if form.is_valid():
            # it is a valid badge
            if form.badge.helper:
                # normal badge with helper -> do it
                item.add_to_helper(form.badge.helper)

                # update saved data in session
                request.session["inventory_helper_pk"] = str(form.badge.helper.pk)
                request.session["inventory_item_name"] = item.name

                return redirect("inventory:register", event_url_name)
            else:
                # no helper -> special badge
                special_badge = True
    except (KeyError, Item.DoesNotExist):
        form = None
    except AlreadyAssigned:
        already_assigned = True

    context = {"event": event, "form": form, "already_assigned": already_assigned, "special_badge": special_badge}
    return render(request, "inventory/register_badge.html", context)

src/inventory/views/settings.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import never_cache

from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event
from registration.permissions import has_access, ACCESS_INVENTORY_EDIT

from ..forms import InventorySettingsForm
from .utils import notactive


@login_required
@never_cache
@archived_not_available
def event_settings(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_EDIT):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    form = InventorySettingsForm(request.POST or None, instance=event.inventory_settings)
    if form.is_valid():
        form.save()
        return redirect("inventory:event_settings", event_url_name)

    context = {"event": event, "form": form}
    return render(request, "inventory/event_settings.html", context)

src/inventory/views/take_back.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import never_cache

from badges.forms import BadgeBarcodeForm
from helfertool.utils import nopermission
from inventory.exceptions import WrongHelper, InvalidMultipleAssignment, NotAssigned
from registration.decorators import archived_not_available
from registration.models import Event, Helper
from registration.permissions import has_access, ACCESS_INVENTORY_HANDLE

from ..forms import InventoryBarcodeForm
from ..models import Item, UsedItem
from .utils import notactive


@login_required
@never_cache
@archived_not_available
def take_back_item(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    last_helper_pk = request.session.pop("inventory_helper_pk", None)
    try:
        last_helper = Helper.objects.get(pk=last_helper_pk)
        last_helper_items = UsedItem.objects.filter(helper=last_helper, timestamp_returned=None)
    except Helper.DoesNotExist:
        last_helper = None
        last_helper_items = None

    form = InventoryBarcodeForm(request.POST or None, event=event)

    not_in_use = False
    if form.is_valid():
        if form.item.is_in_use(event):
            return redirect("inventory:take_back_badge", event_url_name, form.item.pk)
        else:
            not_in_use = True

    context = {
        "event": event,
        "form": form,
        "not_in_use": not_in_use,
        "last_helper": last_helper,
        "last_helper_items": last_helper_items,
    }
    return render(request, "inventory/take_back_item.html", context)


@login_required
@never_cache
@archived_not_available
def take_back_badge(request, event_url_name, item_pk):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    wrong_helper = False
    item = None
    try:
        item = Item.objects.get(pk=item_pk)

        form = BadgeBarcodeForm(request.POST or None, event=event)

        if form.is_valid():
            if form.badge.helper:
                item.remove_from_helper(form.badge.helper)

                request.session["inventory_helper_pk"] = str(form.badge.helper.pk)

                return redirect("inventory:take_back", event_url_name)
            else:
                # special badge -> just show wrong helper message
                wrong_helper = True
    except (KeyError, Item.DoesNotExist):
        form = None
    except WrongHelper:
        wrong_helper = True

    context = {"event": event, "form": form, "item": item, "wrong_helper": wrong_helper}
    return render(request, "inventory/take_back_badge.html", context)


@login_required
@never_cache
@archived_not_available
def take_back_direct(request, event_url_name, item_pk):
    event = get_object_or_404(Event, url_name=event_url_name)

    # check permission
    if not has_access(request.user, event, ACCESS_INVENTORY_HANDLE):
        return nopermission(request)

    # check if badge system is active
    if not event.inventory:
        return notactive(request)

    item = Item.objects.get(pk=item_pk)

    try:
        helper = item.get_exclusive_user(event)

        item.remove_from_helper(helper)

        request.session["inventory_helper_pk"] = str(helper.pk)

        return redirect("inventory:take_back", event_url_name)
    except InvalidMultipleAssignment:
        error = "multiple"
    except NotAssigned:
        error = "noassignment"

    context = {"event": event, "error": error}
    return render(request, "inventory/take_back_error.html", context)

src/inventory/templates/inventory/admin/delete_inventory.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons %}

{% block content %}
    <h1>{% trans "Delete inventory" %}</h1>

    <div class="row">
        <div class="col-xs-12 col-xl-6">
            <table class="table" aria-label="{% trans 'Data of inventory' %}">
                <tr>
                    <th scope="row">{% trans "Name" %}</th>
                    <td>{{ inventory.name }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Admins" %}</th>
                    <td>
                        {% for admin in inventory.admins.all %}
                            {{ admin.get_full_name }}<br/>
                        {% endfor %}
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form_errors form %}
        <button type="submit" class="btn btn-outline-danger">{% icon "trash-alt" %} {% trans "Delete" %}</button>
    </form>
{% endblock %}

src/inventory/templates/inventory/admin/delete_item.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons %}

{% block content %}
    <h1>{% trans "Delete item" %}</h1>

    <div class="row">
        <div class="col-xs-12 col-xl-6">
            <table class="table" aria-label="{% trans 'Data of inventory item' %}">
                <tr>
                    <th scope="row">{% trans "Inventory" %}</th>
                    <td>{{ item.inventory.name }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Name" %}</th>
                    <td>{{ item.name }}</td>
                </tr>
                <tr>
                    <th scope="row">{% trans "Barcode" %}</th>
                    <td>{{ item.barcode }}</td>
                </tr>
            </table>
        </div>
    </div>

    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form_errors form %}
        <button type="submit" class="btn btn-outline-danger">{% icon "trash-alt" %} {% trans "Delete" %}</button>
    </form>
{% endblock %}

src/inventory/templates/inventory/admin/edit_inventory.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons %}

{% block content %}
    <h1>{% trans "Inventory" %}</h1>

    <form action="" method="post">
        {% csrf_token %}

        {% bootstrap_form form layout="floating" %}

        <button type="submit" class="btn btn-outline-primary">{% icon "save" %} {% trans "Save" %}</button>
    </form>
{% endblock %}

src/inventory/templates/inventory/admin/edit_item.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons %}

{% block content %}
    <h1>{% trans "Item" %}</h1>

    <form action="" method="post">
        {% csrf_token %}

        {% bootstrap_form form layout="floating" %}

        <button type="submit" class="btn btn-outline-primary">{% icon "save" %} {% trans "Save" %}</button>
    </form>
{% endblock %}

src/inventory/templates/inventory/admin/inventory_items.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons inventory %}

{% block content %}
    <h1>{% trans "Inventory" %}: {{ inventory.name }}</h1>

    <p><a href="{% url 'inventory:new_item' inventory.pk %}">
        {% icon "plus" %}
        {% trans "New item" %}
    </a></p>

    {% if items %}
        <ul class="list-group">
            {% for item in items %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-8 col-lg-9 col-xl-10">
                        <div class="row">
                            <div class="col-12 col-md-4 py-1 text-break">
                                {{ item.name }}
                            </div>
                            <div class="col-12 col-md-4 py-1">
                                <code>{% icon "barcode" %} {{ item.barcode }}</code>
                            </div>
                            {% if item.comment %}
                            <div class="col-12 col-md-4 py-1 text-break">
                                {{ item.comment|truncatechars:20|linebreaks }}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-4 col-lg-3 col-xl-2 text-nowrap">
                        <a href="{% url "inventory:edit_item" inventory.pk item.pk %}">
                            {% icon "pencil-alt" %}
                            {% trans "Edit" %}
                        </a>

                        <br />

                        <a href="{% url "inventory:delete_item" inventory.pk item.pk %}">
                            {% icon "trash-alt" %}
                            {% trans "Delete" %}
                        </a>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="text-muted">{% trans "There are no items." %}</p>
    {% endif %}
{% endblock %}

src/inventory/templates/inventory/admin/inventory_list.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons inventory %}

{% block content %}
    <h1 id="inventory-header">{% trans "Inventory" %}</h1>

    <p><a href="{% url 'inventory:new_inventory' %}">
        {% icon "plus" %}
        {% trans "New inventory" %}
    </a></p>

    {% if inventories %}
        <ul class="list-group">
            {% for inventory in inventories %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-8 col-lg-9 col-xl-10">
                        <div class="row">
                            <div class="col-12 col-md-6 py-1 text-break">
                                {{ inventory.name }}
                            </div>
                            <div class="col-12 col-md-6 py-1">
                                <ul class="reset-list">
                                    {% for admin in inventory.admins.all %}
                                        <li>{{ admin.get_full_name }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 col-lg-3 col-xl-2 text-nowrap">
                        {% is_inventory_admin inventory as is_admin %}
                        {% if is_admin %}
                            <a href="{% url "inventory:inventory_items" inventory.pk %}">
                                {% icon "list" %}
                                {% comment %}Translators: List verb{% endcomment %}
                                {% trans "List" %}
                            </a>

                            <br />

                            <a href="{% url "inventory:edit_inventory" inventory.pk %}">
                                {% icon "pencil-alt" %}
                                {% trans "Edit" %}
                            </a>

                            <br />

                            <a href="{% url "inventory:delete_inventory" inventory.pk %}">
                                {% icon "trash-alt" %}
                                {% trans "Delete" %}
                            </a>
                        {% endif %}
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="text-muted">{% trans "There is no inventory." %}</p>
    {% endif %}
{% endblock %}