src/helfertool/urls.py
from django.conf import settings
from django.urls import include, path, register_converter
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.defaults import page_not_found, server_error, permission_denied, bad_request
from django.views.generic import TemplateView

from .converters import DateConverter

register_converter(DateConverter, "date")

urlpatterns = [
    # django admin interface
    path("manage/django/", admin.site.urls),
    # internationalization
    path("i18n/", include("django.conf.urls.i18n")),
    # django-select2
    path("select2/", include("django_select2.urls")),
    # django-simple-captcha
    path("captcha/", include("captcha.urls")),
    # authentication
    path("login/", auth_views.LoginView.as_view(template_name="helfertool/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    # apps without event name in url
    path("manage/settings/", include("toolsettings.urls")),
    path("manage/account/", include("account.urls")),
]

# add oidc urls if enabled
if settings.OIDC_CUSTOM_PROVIDER_NAME is not None:
    urlpatterns += [
        path("oidc/", include("mozilla_django_oidc.urls")),
        path(
            "oidc/failed",
            TemplateView.as_view(template_name="helfertool/login_oidc_failed.html"),
            name="oidc_failed",
        ),
    ]

# this is placed at the end to prevent that event names overwrite other urls
urlpatterns += [
    path("", include("help.urls")),
    path("", include("news.urls")),
    path("", include("registration.urls")),
    path("", include("statistic.urls")),
    path("", include("badges.urls")),
    path("", include("gifts.urls")),
    path("", include("inventory.urls")),
    path("", include("mail.urls")),
    path("", include("prerequisites.urls")),
    path("", include("toollog.urls")),
    path("", include("adminautomation.urls")),
]

# for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL + "public", document_root=settings.MEDIA_ROOT / "public")

    urlpatterns += [
        path("errors/400/", bad_request, {"exception": None}),
        path("errors/403/", permission_denied, {"exception": None}),
        path("errors/404/", page_not_found, {"exception": None}),
        path("errors/500/", server_error),
        path(
            "errors/banned/",
            TemplateView.as_view(template_name="helfertool/login_banned.html"),
        ),
    ]

src/help/urls.py
from django.urls import path

from . import views

app_name = "help"
urlpatterns = [
    path("help/", views.create_issue, name="create_issue"),
]

src/statistic/urls.py
from django.urls import path

from . import views

app_name = "statistic"
urlpatterns = [
    path("<slug:event_url_name>/statistics/", views.overview, name="overview"),
    path("<slug:event_url_name>/statistics/chart/timeline/", views.chart_timeline, name="chart_timeline"),
    path("<slug:event_url_name>/statistics/chart/helpers/", views.chart_helpers, name="chart_helpers"),
    path("<slug:event_url_name>/statistics/chart/shifts/", views.chart_shifts, name="chart_shifts"),
    path(
        "<slug:event_url_name>/statistics/chart/eatinghabits/",
        views.chart_nutrition,
        name="chart_nutrition",
    ),
    path("<slug:event_url_name>/shirts/", views.shirts, name="shirts"),
    path("<slug:event_url_name>/nutrition/", views.nutrition, name="nutrition"),
]

src/statistic/views/chart.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext as _
from django.views.decorators.cache import never_cache

from badges.models import SpecialBadges
from registration.decorators import archived_not_available
from registration.models import Event, Shift, HelperShift, Helper
from registration.permissions import has_access, ACCESS_STATISTICS_VIEW
from statistic.views.nutrition import NutritionData

from datetime import timedelta
from itertools import cycle


# colors
# TODO: get from theming config, if this is implemented
colors_primary = [
    "#1A876E",
    "#F5BE16",
    "#E747F5",
    "#A88518",
    "#2FF5C7",
]

colors_danger = [
    "#d53e54",
    "#d53e54",
    "#d5939d",
]


def _chart_doughnut(data):
    """
    Return JSON for chart.js doughnut char.

    data = [
        {
            "value": 10,
            "labal": "Test",
            "danger": False,  # optional
        },
        ...
    ]
    """
    # colors:
    primary = cycle(colors_primary)
    danger = cycle(colors_danger)

    # prepare data for chart.js
    values = [d["value"] for d in data]
    labels = [d["label"] for d in data]

    colors = []
    for d in data:
        if d.get("danger", False):
            colors.append(next(danger))
        else:
            colors.append(next(primary))

    # json for chart.js
    output = {
        "type": "doughnut",
        "data": {
            "datasets": [
                {
                    "data": values,
                    "backgroundColor": colors,
                },
            ],
            "labels": labels,
        },
        "options": {
            "cutout": "60%",
        },
    }

    return JsonResponse(output)


@login_required
@never_cache
@archived_not_available
def chart_timeline(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # permission
    if not has_access(request.user, event, ACCESS_STATISTICS_VIEW):
        return JsonResponse({})

    # collect data
    timeline = {}
    for helper in event.helper_set.all():
        if not helper.is_coordinator:
            day = helper.timestamp.strftime("%Y-%m-%d")
            if day in timeline:
                timeline[day] += 1
            else:
                timeline[day] = 1

    # abort if no data found
    if len(timeline) == 0:
        return JsonResponse({})

    # add "0" value on day before first registration
    day_one = event.helper_set.order_by("timestamp").first().timestamp
    day_zero = day_one - timedelta(days=1)
    timeline[day_zero.strftime("%Y-%m-%d")] = 0

    # sum up the days
    timeline_sum_data = []
    days = sorted(timeline.keys())
    cur_sum = 0
    for day in days:
        cur_sum += timeline[day]

        timeline_sum_data.append(
            {
                "x": day,
                "y": cur_sum,
            }
        )

    # output format
    output = {
        "type": "line",
        "data": {
            "datasets": [
                {
                    "label": _("Number of helpers"),
                    "data": timeline_sum_data,
                    "borderColor": colors_primary[0],
                    "lineTension": 0.3,
                },
            ]
        },
        "options": {
            "scales": {
                "x": {
                    "type": "time",
                },
                "y": {
                    "ticks": {
                        "precision": 0,
                    }
                },
            },
            "plugins": {
                "legend": {
                    "display": False,
                }
            },
            "maintainAspectRatio": False,
        },
    }

    return JsonResponse(output)


@login_required
@never_cache
@archived_not_available
def chart_helpers(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # permission
    if not has_access(request.user, event, ACCESS_STATISTICS_VIEW):
        return JsonResponse({})

    # get data
    total_helpers = event.helper_set.count()

    num_coordinators = event.all_coordinators.count()
    num_helpers = total_helpers - num_coordinators

    if event.badges:
        num_specialbadges = SpecialBadges.objects.filter(event=event).aggregate(Sum("number"))["number__sum"] or 0
    else:
        num_specialbadges = 0

    # abort if nothing to show
    if total_helpers + num_specialbadges == 0:
        return JsonResponse({})

    # output format
    data = [
        {"value": num_helpers, "label": _("Helpers")},
        {"value": num_coordinators, "label": _("Coordinators")},
    ]
    if num_coordinators:
        data.append({"value": num_specialbadges, "label": _("Special badges")})

    return _chart_doughnut(data)


@login_required
@never_cache
@archived_not_available
def chart_shifts(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # permission
    if not has_access(request.user, event, ACCESS_STATISTICS_VIEW):
        return JsonResponse({})

    # get data
    total_shifts = Shift.objects.filter(job__event=event).aggregate(Sum("number"))["number__sum"] or 0
    filled_shifts = HelperShift.objects.filter(helper__event=event).count()
    vacant_shifts = total_shifts - filled_shifts

    # abort if nothing to show
    if total_shifts == 0:
        return JsonResponse({})

    # output format
    data = [
        {"value": filled_shifts, "label": _("Filled slots")},
        {"value": vacant_shifts, "label": _("Vacant slots"), "danger": True},
    ]

    return _chart_doughnut(data)


@login_required
@never_cache
@archived_not_available
def chart_nutrition(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # permission
    if not has_access(request.user, event, ACCESS_STATISTICS_VIEW):
        return JsonResponse({})

    if not event.ask_nutrition:
        JsonResponse({})

    # get data
    data = NutritionData(event.helper_set)

    # abort if nothing to show
    if event.helper_set.count() == 0:
        return JsonResponse({})

    # output format
    response = [
        {"value": data.num_no_preference, "label": _("No preference")},
        # Translators: adjective
        {"value": data.num_vegetarian, "label": _("Vegetarian")},
        {"value": data.num_vegan, "label": _("Vegan")},
        {"value": data.num_other, "label": _("Other")},
    ]

    # Showing the number of responses where no preference is specified is only relevant if the
    # event is later changed to ask for nutrition preferences, so we only show it if there are
    # any such responses.
    if data.num_blank > 0:
        response.append({"value": data.num_blank, "label": _("Not specified")})

    return _chart_doughnut(response)

src/statistic/views/nutrition.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import never_cache

from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event, Helper
from registration.permissions import has_access, has_access_event_or_job, ACCESS_STATISTICS_VIEW

from collections import OrderedDict


class NutritionData:
    """Prepare numbers about chosen nutrition for template."""

    def __init__(self, helper_set):
        # numbers
        self.num_blank = helper_set.filter(nutrition=None).count()
        self.num_no_preference = helper_set.filter(nutrition=Helper.NUTRITION_NO_PREFERENCE).count()
        self.num_vegetarian = helper_set.filter(nutrition=Helper.NUTRITION_VEGETARIAN).count()
        self.num_vegan = helper_set.filter(nutrition=Helper.NUTRITION_VEGAN).count()
        self.num_other = helper_set.filter(nutrition=Helper.NUTRITION_OTHER).count()

        # helpers with "other" (we want to show the comments)
        self.helpers_other = helper_set.filter(nutrition=Helper.NUTRITION_OTHER)


@login_required
@never_cache
@archived_not_available
def nutrition(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # permission
    if not has_access_event_or_job(request.user, event, ACCESS_STATISTICS_VIEW):
        return nopermission(request)

    # check if nutrition is collected for this event
    if not event.ask_nutrition:
        context = {"event": event}
        return render(request, "statistic/nutrition_not_active.html", context)

    # event wide
    event_data = None
    if has_access(request.user, event, ACCESS_STATISTICS_VIEW):
        event_data = NutritionData(event.helper_set)

    # for each job
    job_data = OrderedDict()
    for job in event.job_set.all():
        # check permission for job
        if not has_access(request.user, job, ACCESS_STATISTICS_VIEW):
            continue

        job_data[job] = NutritionData(job.helpers_and_coordinators())

    # render
    context = {"event": event, "event_data": event_data, "job_data": job_data}
    return render(request, "statistic/nutrition.html", context)

src/statistic/views/overview.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import never_cache

from badges.models import SpecialBadges
from helfertool.utils import nopermission
from registration.decorators import archived_not_available
from registration.models import Event, Shift
from registration.permissions import has_access, ACCESS_STATISTICS_VIEW


@login_required
@never_cache
@archived_not_available
def overview(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)

    # permission
    if not has_access(request.user, event, ACCESS_STATISTICS_VIEW):
        return nopermission(request)

    # get data, that we need outside of chart.js
    num_people = event.helper_set.count()
    if event.badges:
        num_people += SpecialBadges.objects.filter(event=event).aggregate(Sum("number"))["number__sum"] or 0

    num_shift_slots = Shift.objects.filter(job__event=event).aggregate(Sum("number"))["number__sum"] or 0

    # render
    context = {
        "event": event,
        "num_people": num_people,
        "num_shift_slots": num_shift_slots,
    }
    return render(request, "statistic/overview.html", context)

src/statistic/views/shirts.py
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import never_cache

from helfertool.utils import nopermission
from registration.models import Event, EventArchive, Helper
from registration.permissions import has_access, has_access_event_or_job, ACCESS_STATISTICS_VIEW

from collections import OrderedDict


class JobShirts:
    def __init__(self, shirt_choices):
        self.shifts = OrderedDict()
        self.total = OrderedDict()

        for size, name in shirt_choices:
            self.total.update({name: 0})


@login_required
@never_cache
def shirts(request, event_url_name):
    event = get_object_or_404(Event, url_name=event_url_name)
    shirt_choices = event.get_shirt_choices()

    # permission
    if not has_access_event_or_job(request.user, event, ACCESS_STATISTICS_VIEW):
        return nopermission(request)

    # check if shirt sizes are collected for this event
    if not event.ask_shirt:
        context = {"event": event}
        return render(request, "statistic/shirts_not_active.html", context)

    # size names
    size_names = [name for size, name in shirt_choices]

    # collect data
    # size -> {"all": 40, "coordinators": 10}
    total_shirts = OrderedDict()

    job_shirts = OrderedDict()

    # different data sources depending on archive flag
    if event.archived:
        # if event is archived, just get the summary data from the archive
        try:
            archive_data = EventArchive.objects.get(event=event, key="shirts", version=1).data
            for size, name in shirt_choices:
                total_shirts.update({name: {"all": archive_data.get(size, 0), "coordinators": None}})
        except EventArchive.DoesNotExist:
            # no data archived -> no output
            pass
    else:
        # event is not archived -> collect detailed data
        # event wide
        if has_access(request.user, event, ACCESS_STATISTICS_VIEW):
            # shirt sizes
            total_shirts_query = event.helper_set.values("shirt").annotate(num=Count("shirt")).order_by()
            coordinator_shirts_query = event.all_coordinators.values("shirt").annotate(num=Count("shirt")).order_by()

            # total numbers (iterate over all sizes in correct order)
            for size, name in shirt_choices:
                num_total = 0
                num_coordinator = 0

                try:
                    num_total = total_shirts_query.get(shirt=size)["num"]
                except Helper.DoesNotExist:
                    pass

                try:
                    num_coordinator = coordinator_shirts_query.get(shirt=size)["num"]
                except Helper.DoesNotExist:
                    pass

                total_shirts.update({name: {"all": num_total, "coordinators": num_coordinator}})

        # for each job
        for job in event.job_set.all():
            # check permission for job
            if not has_access(request.user, job, ACCESS_STATISTICS_VIEW):
                continue

            sizes_for_job = JobShirts(shirt_choices)
            # for each shift
            for shift in job.shift_set.all():
                sizes_for_shift = shift.shirt_sizes
                sizes_for_job.shifts.update({shift: sizes_for_shift})

                # update total number
                for size, name in shirt_choices:
                    num = sizes_for_job.total[name]
                    sizes_for_job.total.update({name: num + sizes_for_shift[name]})
            job_shirts.update({job: sizes_for_job})

    # render
    context = {"event": event, "size_names": size_names, "total_shirts": total_shirts, "job_shirts": job_shirts}
    return render(request, "statistic/shirts.html", context)

src/statistic/templates/statistic/nutrition.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons %}

{% block content %}
    <h1>{% trans "Nutrition" %}</h1>

    {% if event_data %}
        <h2>{% trans "Total" %}</h2>
        {% include "statistic/nutrition_table.html" with data=event_data %}
    {% endif %}

    {% if job_data %}
        <h2>{% trans "Per job" %}</h2>

        <div class="alert alert-secondary">
            <strong>{% trans "Info:" %}</strong>
            {% blocktrans trimmed %}
                Helpers and coordinators are counted for all their jobs.
                If you sum up the numbers here, they might be higher than the total numbers.
            {% endblocktrans %}
        </div>

        {% for job,data in job_data.items %}
            <h3>{{ job.name }}</h3>
            {% include "statistic/nutrition_table.html" with data=data job=job %}
        {% endfor %}
    {% endif %}
{% endblock %}

src/statistic/templates/statistic/nutrition_not_active.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <h1>{% trans "Nutrition" %}</h1>

    <div class="alert alert-danger" role="alert">
        {% trans "For this event no nutrition prefences were collected." %}
    </div>
{% endblock %}

src/statistic/templates/statistic/nutrition_table.html
{% load i18n icons %}

{# included in nutrition.html #}

{# table with numbers #}
<div class="row">
    <div class="col-xs-12 col-xl-6">
        <table class="table" aria-label="{% trans "Nutrition for helpers" %}">
            <tr>
                <th scope="row" class="w-50">{% trans "No preference" %}</th>
                <td scope="row" class="w-50">{{ data.num_no_preference }}</td>
            </tr>
            <tr>
                <th scope="row" class="w-50">{% trans "Vegetarian" %}</th>
                <td scope="row" class="w-50">{{ data.num_vegetarian }}</td>
            </tr>
            <tr>
                <th scope="row" class="w-50">{% trans "Vegan" %}</th>
                <td scope="row" class="w-50">{{ data.num_vegan }}</td>
            </tr>
            <tr>
                <th scope="row" class="w-50">{% trans "Other" %}</th>
                <td scope="row" class="w-50">
                    {{ data.num_other }}

                    {% if data.helpers_other %}
                        (<a href="" data-bs-toggle="modal"
                            data-bs-target="#nutrition-{% if job %}{{ job.pk }}{% else %}total{% endif %}">{% trans "Show" %}</a>)
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
</div>


{# modal dialog with comments #}
<div class="modal fade" id="nutrition-{% if job %}{{ job.pk }}{% else %}total{% endif %}" tabindex="-1"
     aria-labelledby="nutrition-{% if job %}{{ job.pk }}{% else %}total{% endif %}-label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="nutrition-{% if job %}{{ job.pk }}{% else %}total{% endif %}-label">
                    {% if job %}
                        {% blocktrans trimmed with name=job.name %}
                            Other nutrition for {{ name }}
                        {% endblocktrans %}
                    {% else %}
                        {% trans "Other nutrition for complete event" %}
                    {% endif %}
                </h5>
            </div>
            <div class="modal-body">
                <ul class="list-group">
                    {% for helper in data.helpers_other %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-12 col-md-4 py-1 text-break">
                                <a href="{% url 'view_helper' event.url_name helper.pk %}">{{ helper.full_name }}</a>
                            </div>
                            <div class="col-12 col-md-8 py-1 text-break">
                                {{ helper.comment | default:"-" }}
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">{% icon "times" %} {% trans "Close" %}</button>
            </div>
        </div>
    </div>
</div>

src/statistic/templates/statistic/overview.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 static %}

{% block content %}
    <h1>{% trans "Statistics" %}</h1>

    <div class="row">
        <div class="col-lg-6 col-xxl-4 statistics">
            <div class="title">{% trans "People" %}</div>

            <canvas class="chart" data-url="{% url 'statistic:chart_helpers' event.url_name %}" data-empty="helpers_empty"></canvas>
            <div id="helpers_empty" class="placeholdertext d-none">{% trans "There are no helpers." %}</div>

            {% if num_people %}
                <div class="details">{% trans "Total number of people" %}: {{ num_people }}</div>
            {% endif %}
        </div>

        <div class="col-lg-6 col-xxl-4 statistics">
            <div class="title">{% trans "Shifts" %}</div>

            <canvas class="chart" data-url="{% url 'statistic:chart_shifts' event.url_name %}" data-empty="shifts_empty"></canvas>
            <div id="shifts_empty" class="placeholdertext d-none">{% trans "There are no shifts." %}</div>

            {% if num_shift_slots %}
                <div class="details">{% trans "Total number of shift slots" %}: {{ num_shift_slots }}</div>
            {% endif %}
        </div>

        {% if event.ask_nutrition %}
        <div class="col-lg-6 col-xxl-4 statistics">
            <div class="title">{% trans "Nutrition" %}</div>

            <canvas class="chart" data-url="{% url 'statistic:chart_nutrition' event.url_name %}" data-empty="nutrition_empty"></canvas>
            <div id="nutrition_empty" class="placeholdertext d-none">{% trans "There are no helpers." %}</div>
        </div>
        {% endif %}
    </div>

    <div class="row">
        <div class="col-12 statistics">
            <div class="title">{% trans "Timeline of registrations" %}</div>
            <div class="timeline-wrapper">
                <canvas class="chart" data-url="{% url 'statistic:chart_timeline' event.url_name %}" data-empty="overview_empty"></canvas>
                <div id="overview_empty" class="placeholdertext d-none">{% trans "There are no helpers." %}</div>
            </div>
        </div>
    </div>

    <script src="{% static "statistic/js/chart.js" %}"></script>
{% endblock %}

src/statistic/templates/statistic/shirts.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 icons %}

{% block content %}
    <h1>{% trans "T-Shirts" %}</h1>

    {% if not total_shirts and not job_shirts %}
        <div class="alert alert-info" role="alert">
            {% trans "No data available." %}
        </div>
    {% endif %}

    {% if total_shirts %}
        <h2>{% trans "Total" %}</h2>

        <div class="row">
            <div class="col-xs-12 col-xl-6">
                <table class="table" aria-label="{% trans "T-shirt sizes of all helpers and coordinators" %}">
                    <tr>
                        <th scope="col" class="w-25">{% trans "Size" %}</th>
                        <th scope="col" class="w-25">{% trans "Helpers and coordinators" %}</th>
                        {% if not event.archived %}
                            <th scope="col" class="w-25">{% trans "Only coordinators" %}</th>
                        {% endif %}
                    </tr>

                    {% for size, data in total_shirts.items %}
                        <tr>
                            <td>{{ size }}</td>
                            <td>{{ data.all }}</td>
                            {% if not event.archived %}
                                <td>{{ data.coordinators }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    {% endif %}

    {% if job_shirts %}
        <h2>{% trans "Helpers (without coordinators)" %}</h2>

        <div class="alert alert-secondary">
            <strong>{% trans "Info:" %}</strong>
            {% trans "The T-shirt of a helper is counted for the job with the first shift." %}
        </div>

        {% for job,data in job_shirts.items %}
            <h3>{{ job.name }}</h3>

            {# summary for job #}
            <div class="row">
                <div class="col-xs-12 col-xl-6">
                    <table class="table" aria-label="{% trans "T-shirt sizes for job" %}">
                        <tr>
                            <th scope="col" class="w-25">{% trans "Size" %}</th>
                            <th scope="col" class="w-25">{% trans "Helpers" %}</th>
                            {% if not event.archived %}
                                {# same colunm width as above #}
                                <th scope="col" class="w-25"></th>
                            {% endif %}
                        </tr>

                        {% for size,num in data.total.items %}
                            <tr>
                                <td>{{ size }}</td>
                                <td>{{ num }}</td>
                                {% if not event.archived %}
                                    <td></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>

            {# details per shift #}
            <button type="button" class="btn btn-outline-primary mt-1 mb-3" data-bs-toggle="modal" data-bs-target="#sizes-{{ job.pk }}">
                {% icon "list" %} {% trans "Sizes per shift" %}
            </button>

            <div class="modal fade" id="sizes-{{ job.pk }}" tabindex="-1" aria-labelledby="sizes-{{ job.pk }}-label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-scrollable modal-xl">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="sizes-{{ job.pk }}-label">
                                {% blocktrans trimmed with name=job.name %}
                                    T-Shirt sizes for {{ name }}
                                {% endblocktrans %}
                            </h5>
                        </div>
                        <div class="modal-body">
                            <ul class="list-group">
                                {% for shift,sizes_for_shift in data.shifts.items %}
                                <li class="list-group-item">
                                    <div class="row">
                                        <div class="col-12 col-md-4 py-1 text-break">
                                            {{ shift.time_with_day }}
                                            {% if shift.name %}
                                                <br/>{{ shift.name }}
                                            {% endif %}
                                        </div>
                                        <div class="col-12 col-md-8 py-1">
                                            {% for size,num in sizes_for_shift.items %}
                                                {% if num > 0 %}
                                                    <span class="badge badge-outline-secondary shirt-badge">
                                                        {{ num }}x {{ size }}
                                                    </span>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">{% icon "times" %} {% trans "Close" %}</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

src/statistic/templates/statistic/shirts_not_active.html
{% extends "helfertool/admin.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <h1>{% trans "T-Shirts" %}</h1>

    <div class="alert alert-danger" role="alert">
        {% trans "For this event no t-shirt sizes were collected." %}
    </div>
{% endblock %}