src/badges/urls.py
from django.urls import path

from . import views

app_name = "badges"
urlpatterns = [
    #
    # settings
    #
    path("<slug:event_url_name>/badges/settings/", views.settings, name="settings"),
    path("<slug:event_url_name>/badges/settings/advanced/", views.settings_advanced, name="settings_advanced"),
    path("<slug:event_url_name>/badges/defaulttemplate/", views.default_template, name="default_template"),
    path("<slug:event_url_name>/badges/currenttemplate/", views.current_template, name="current_template"),
    #
    # edit badge
    #
    path(
        "<slug:event_url_name>/helpers/<uuid:helper_pk>/badge/",
        views.edit_badge,
        name="edit_badge",
    ),
    path(
        "<slug:event_url_name>/helpers/<uuid:helper_pk>/badge/photo/",
        views.get_badge_photo,
        name="get_badge_photo",
    ),
    #
    # permission
    #
    path(
        "<slug:event_url_name>/badges/permission/<int:permission_pk>/",
        views.edit_permission,
        name="edit_permission",
    ),
    path("<slug:event_url_name>/badges/permission/add/", views.edit_permission, name="new_permission"),
    path(
        "<slug:event_url_name>/badges/permission/<int:permission_pk>/delete/",
        views.delete_permission,
        name="delete_permission",
    ),
    #
    # role
    #
    path("<slug:event_url_name>/badges/role/<int:role_pk>/", views.edit_role, name="edit_role"),
    path("<slug:event_url_name>/badges/role/add/", views.edit_role, name="new_role"),
    path(
        "<slug:event_url_name>/badges/role/<int:role_pk>/delete/",
        views.delete_role,
        name="delete_role",
    ),
    #
    # design
    #
    path(
        "<slug:event_url_name>/badges/design/<int:design_pk>/",
        views.edit_design,
        name="edit_design",
    ),
    path("<slug:event_url_name>/badges/design/add/", views.edit_design, name="new_design"),
    path(
        "<slug:event_url_name>/badges/design/<int:design_pk>/delete/",
        views.delete_design,
        name="delete_design",
    ),
    path(
        "<slug:event_url_name>/badges/design/<int:design_pk>/bg/<side>/",
        views.get_design_bg,
        name="get_design_bg",
    ),
    #
    # badge generation
    #
    # overview page
    path("<slug:event_url_name>/badges/", views.index, name="index"),
    # overview of generated badges (list of tasks)
    path("<slug:event_url_name>/badges/tasklist/", views.tasklist, name="tasklist"),
    # warnings
    path("<slug:event_url_name>/badges/warnings/<int:job_pk>/", views.warnings, name="warnings"),
    # generate for job
    path(
        "<slug:event_url_name>/badges/generate/<int:job_pk>/",
        views.generate,
        {"generate": "job"},
        name="generate_for_job",
    ),
    path(
        "<slug:event_url_name>/badges/generate/<int:job_pk>/all/",
        views.generate,
        {"generate": "job", "skip_printed": False},
        name="generate_all_for_job",
    ),
    # generate special badges
    path(
        "<slug:event_url_name>/badges/generate/special/",
        views.generate,
        {"generate": "special"},
        name="generate_special",
    ),
    path(
        "<slug:event_url_name>/badges/generate/special/all/",
        views.generate,
        {"generate": "special", "skip_printed": False},
        name="generate_all_special",
    ),
    # generate for all jobs and special badges
    path("<slug:event_url_name>/badges/generate/", views.generate, {"generate": "all"}, name="generate"),
    path(
        "<slug:event_url_name>/badges/generate/all/",
        views.generate,
        {"generate": "all", "skip_printed": False},
        name="generate_all",
    ),
    # failed page
    path("<slug:event_url_name>/badges/failed/<task_id>/", views.failed, name="failed"),
    # download badges
    path(
        "<slug:event_url_name>/badges/download/<task_id>/",
        views.download,
        name="download",
    ),
    #
    # register badges
    #
    path("<slug:event_url_name>/badges/register/", views.register, name="register"),
    #
    # special badges
    #
    path("<slug:event_url_name>/badges/special/", views.list_specialbadges, name="list_specialbadges"),
    path(
        "<slug:event_url_name>/badges/special/<int:specialbadges_pk>/",
        views.edit_specialbadges,
        name="edit_specialbadges",
    ),
    path("<slug:event_url_name>/badges/special/add/", views.edit_specialbadges, name="new_specialbadges"),
    path(
        "<slug:event_url_name>/badges/special/<int:specialbadges_pk>/template/",
        views.edit_specialbadges_template,
        name="edit_specialbadges_template",
    ),
    path(
        "<slug:event_url_name>/badges/special/<int:specialbadges_pk>/delete/",
        views.delete_specialbadges,
        name="delete_specialbadges",
    ),
    path(
        "<slug:event_url_name>/badges/special/<int:specialbadges_pk>/template/photo/",
        views.get_specialbadges_photo,
        name="get_specialbadges_photo",
    ),
]

src/gifts/urls.py
from django.urls import path

from . import views

app_name = "gifts"
urlpatterns = [
    #
    # list
    #
    path("<slug:event_url_name>/gifts/", views.list, name="list"),
    #
    # edit gifts
    #
    path("<slug:event_url_name>/gifts/gift/add/", views.edit_gift, name="add_gift"),
    path("<slug:event_url_name>/gifts/gift/<int:gift_pk>/", views.edit_gift, name="edit_gift"),
    path(
        "<slug:event_url_name>/gifts/gift/<int:gift_pk>/delete/",
        views.delete_gift,
        name="delete_gift",
    ),
    #
    # edit gift sets
    #
    path("<slug:event_url_name>/gifts/giftset/add/", views.edit_gift_set, name="add_gift_set"),
    path(
        "<slug:event_url_name>/gifts/giftset/<int:gift_set_pk>/",
        views.edit_gift_set,
        name="edit_gift_set",
    ),
    path(
        "<slug:event_url_name>/gifts/giftset/<int:gift_set_pk>/delete/",
        views.delete_gift_set,
        name="delete_gift_set",
    ),
    #
    # open deposits
    #
    path("<slug:event_url_name>/gifts/deposit/", views.list_deposit, name="list_deposit"),
    #
    # shirts that need to be bought
    #
    path("<slug:event_url_name>/gifts/shirts/", views.list_shirts, name="list_shirts"),
    #
    # set present flag for complete shifts
    #
    path(
        "<slug:event_url_name>/gifts/present/<int:shift_pk>/",
        views.set_present,
        name="set_present",
    ),
]

src/helfertool/urls.py
from django.conf import settings
from django.urls import include, path, register_converter
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.defaults import page_not_found, server_error, permission_denied, bad_request
from django.views.generic import TemplateView

from .converters import DateConverter

register_converter(DateConverter, "date")

urlpatterns = [
    # django admin interface
    path("manage/django/", admin.site.urls),
    # internationalization
    path("i18n/", include("django.conf.urls.i18n")),
    # django-select2
    path("select2/", include("django_select2.urls")),
    # django-simple-captcha
    path("captcha/", include("captcha.urls")),
    # authentication
    path("login/", auth_views.LoginView.as_view(template_name="helfertool/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    # apps without event name in url
    path("manage/settings/", include("toolsettings.urls")),
    path("manage/account/", include("account.urls")),
]

# add oidc urls if enabled
if settings.OIDC_CUSTOM_PROVIDER_NAME is not None:
    urlpatterns += [
        path("oidc/", include("mozilla_django_oidc.urls")),
        path(
            "oidc/failed",
            TemplateView.as_view(template_name="helfertool/login_oidc_failed.html"),
            name="oidc_failed",
        ),
    ]

# this is placed at the end to prevent that event names overwrite other urls
urlpatterns += [
    path("", include("help.urls")),
    path("", include("news.urls")),
    path("", include("registration.urls")),
    path("", include("statistic.urls")),
    path("", include("badges.urls")),
    path("", include("gifts.urls")),
    path("", include("inventory.urls")),
    path("", include("mail.urls")),
    path("", include("prerequisites.urls")),
    path("", include("toollog.urls")),
    path("", include("adminautomation.urls")),
]

# for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL + "public", document_root=settings.MEDIA_ROOT / "public")

    urlpatterns += [
        path("errors/400/", bad_request, {"exception": None}),
        path("errors/403/", permission_denied, {"exception": None}),
        path("errors/404/", page_not_found, {"exception": None}),
        path("errors/500/", server_error),
        path(
            "errors/banned/",
            TemplateView.as_view(template_name="helfertool/login_banned.html"),
        ),
    ]

src/help/urls.py
from django.urls import path

from . import views

app_name = "help"
urlpatterns = [
    path("help/", views.create_issue, name="create_issue"),
]

src/mail/urls.py
from django.urls import path

from . import views

app_name = "mail"
urlpatterns = [
    path("<slug:event_url_name>/mail/", views.send_mail, name="send"),
    path("<slug:event_url_name>/mail/list/", views.list_mails, name="list"),
    path("<slug:event_url_name>/mail/<int:mail_pk>/", views.show_mail, name="show"),
    path(
        "<slug:event_url_name>/mail/<int:mail_pk>/errors/",
        views.show_mail_errors,
        name="show_errors",
    ),
]

src/news/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "news"
urlpatterns = [
    # management
    path("manage/news/", views.send, name="send"),
    path("manage/news/remove/", views.remove, name="remove"),
    path("manage/news/failures/", views.failures, name="failures"),
    # subscribe and unsubcribe
    path("subscribe/", views.subscribe, name="subscribe"),
    path("subscribe/done/", TemplateView.as_view(template_name="news/subscribe_done.html"), name="subscribe_done"),
    path("subscribe/<uuid:token>/", views.subscribe_confirm, name="subscribe_confirm"),
    # empty tokens are allowed since this is used to generate the link once
    # and add the specific tokens
    # empty tokens are handled in the view with an 404
    path("unsubscribe/", views.unsubscribe, name="unsubscribe_empty"),
    path("unsubscribe/<uuid:token>/", views.unsubscribe, name="unsubscribe"),
    path(
        "unsubscribe/done/",
        TemplateView.as_view(template_name="news/unsubscribe_done.html"),
        name="unsubscribe_done",
    ),
]

src/helfertool/forms/fields.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

import os


class RestrictedImageField(models.ImageField):
    """ImageField that restricts the file extensions to jpg, jpeg and png.

    For example, LaTeX does not like some file extensions that users could upload."""

    def validate(self, value, model_instance):
        super().validate(value, model_instance)

        ext = os.path.splitext(value.name)[1].lower()
        if ext not in [".jpg", ".jpeg", ".png"]:
            raise ValidationError(_("File type not supported, use JPG or PNG."))

src/helfertool/forms/widgets.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from django_select2.forms import ModelSelect2Widget, ModelSelect2MultipleWidget
from captcha.fields import CaptchaTextInput


class DatePicker(forms.DateInput):
    """Date picker (browser native)"""

    input_type = "date"

    def __init__(self):
        super(DatePicker, self).__init__(format="%Y-%m-%d")


class DateTimePicker(forms.SplitDateTimeWidget):
    """Date and time picker (separate boxes, browser native)"""

    def __init__(self):
        super(DateTimePicker, self).__init__(
            date_format="%Y-%m-%d",
            date_attrs={"type": "date"},
            time_format="%H:%M",
            time_attrs={"type": "time", "class": "mt-1"},
        )


def user_label_from_instance(obj):
    if obj.first_name and obj.last_name:
        return "{} ({})".format(obj.get_full_name(), obj.get_username())
    return obj.get_username()


class SingleUserSelectWidget(ModelSelect2Widget):
    """Select2 widget for single user."""

    model = get_user_model()

    search_fields = [
        "username__icontains",
        "first_name__icontains",
        "last_name__icontains",
    ]

    def label_from_instance(self, obj):
        return user_label_from_instance(obj)


class UserSelectWidget(ModelSelect2MultipleWidget):
    """Select2 widget for multiple users."""

    model = get_user_model()

    search_fields = [
        "username__icontains",
        "first_name__icontains",
        "last_name__icontains",
    ]

    def label_from_instance(self, obj):
        return user_label_from_instance(obj)


class ImageFileInput(forms.ClearableFileInput):
    """ClearableFileInput that does not show the URL to the current file, but the image instead.

    If the image should be displayed, the parameter download_url must be set in the form
    (it is dynamic, so we cannot guess it here).
    """

    template_name = "helfertool/forms/widgets/image_file_input.html"
    clear_checkbox_label = _("Delete image")

    download_url = None

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context["widget"]["download_url"] = self.download_url
        return context


class CustomCaptchaTextInput(CaptchaTextInput):
    template_name = "helfertool/forms/widgets/captcha.html"

src/helfertool/templates/helfertool/admin_event_menu.html
{% load i18n icons permissions toolsettings %}

{% has_access event "ACCESS_INVOLVED" as involved %}
{% if involved %}
    {% djangosetting "DATABASE_LOGGING" as database_logging %}

    {% has_access event "ACCESS_EVENT_EDIT" as user_event_edit %}
    {% has_access event "ACCESS_EVENT_EDIT_JOBS" as user_event_edit_jobs %}
    {% has_access event "ACCESS_EVENT_EDIT_LINKS" as user_event_edit_links %}
    {% has_access event "ACCESS_EVENT_EDIT_DUPLICATES" as user_event_edit_duplicates %}
    {% has_access_event_or_job event "ACCESS_EVENT_VIEW_COORDINATORS" as user_event_view_coordinators %}
    {% has_access event "ACCESS_EVENT_VIEW_AUDITLOGS" as user_event_view_auditlogs %}
    {% has_access_event_or_job event "ACCESS_MAILS_SEND" as user_mails_send %}
    {% has_access_event_or_job event "ACCESS_MAILS_VIEW" as user_mails_view %}
    {% has_access event "ACCESS_GIFTS_EDIT" as user_gifts_edit %}
    {% has_access event "ACCESS_GIFTS_VIEW_SUMMARY" as user_gifts_view_summary %}
    {% has_access event "ACCESS_BADGES_EDIT" as user_badges_edit %}
    {% has_access event "ACCESS_BADGES_EDIT_SPECIAL" as user_badges_edit_special %}
    {% has_access event "ACCESS_BADGES_GENERATE" as user_badges_generate %}
    {% has_access event "ACCESS_PREREQUISITES_VIEW" as user_prerequisites_view %}
    {% has_access event "ACCESS_INVENTORY_EDIT" as user_inventory_edit %}
    {% has_access event "ACCESS_INVENTORY_HANDLE" as user_inventory_handle %}
    {% has_access event "ACCESS_STATISTICS_VIEW" as user_statistics_view %}
    {% has_access_event_or_job event "ACCESS_STATISTICS_VIEW" as user_statistics_specific %}

<nav id="sidemenu">
    <div class="sidemenu-header">{{ event.name }}</div>

    {% if event and event.archived %}
        <div class="sidemenu-section mb-3">
            <span class="badge bg-secondary">{% icon "archive" %} {% trans "archived" %}</span>
        </div>
    {% endif %}

    <ul class="nav flex-column">
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "General" %}</p>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a href="{% url 'form' event.url_name %}" class="nav-link" target="_blank" rel="noopener">
                        {% icon "external-link-alt" %}
                        {% trans "Go to registration" %}
                    </a>
                </li>

                {% if user_event_edit %}
                <li class="nav-item">
                    <a href="{% url 'edit_event' event.url_name %}" class="nav-link">{% trans "Edit event" %}</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'edit_event_admins' event.url_name %}" class="nav-link">{% trans "Permissions" %}</a>
                </li>
                {% endif %}

                {% if user_event_edit_jobs %}
                <li class="nav-item">
                    <a href="{% url 'jobs_and_shifts' event.url_name %}" class="nav-link">{% trans "Jobs and shifts" %}</a>
                </li>
                {% endif %}

                {% if user_event_edit_links %}
                <li class="nav-item">
                    <a href="{% url 'links' event.url_name %}" class="nav-link">{% trans "Links" %}</a>
                </li>
                {% endif %}

                {% if database_logging and user_event_view_auditlogs %}
                <li class="nav-item">
                    <a href="{% url 'toollog:event_audit_log' event.url_name %}" class="nav-link">{% trans "Audit log" %}</a>
                </li>
                {% endif %}
            </ul>
        </li>

        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Helpers" %}</p>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a href="{% url 'helpers' event.url_name %}" class="nav-link">{% trans "Helpers and coordinators" %}</a>

                    {# list of all (for user visible) jobs #}
                    {% if not event.archived %}
                    {% if request.resolver_match.url_name == "helpers" or request.resolver_match.url_name == "helpers_for_job" %}
                        <ul class="nav flex-column">
                        {% for job in event.job_set.all %}
                            {% has_access job "ACCESS_JOB_VIEW_HELPERS" as job_visible %}
                            {% if job_visible %}
                                <li class="nav-item">
                                    <a href="{% url 'helpers_for_job' event.url_name job.pk %}" class="nav-link">{{ job.name }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                    {% endif %}
                    {% endif %}
                </li>

                {% if not event.archived %}
                    <li class="nav-item">
                        <a href="{% url 'search_helper' event.url_name %}" class="nav-link">{% trans "Search helper" %}</a>
                    </li>

                    {% if user_event_edit_duplicates %}
                    <li class="nav-item">
                        <a href="{% url 'duplicates' event.url_name %}" class="nav-link">{% trans "Duplicates" %}</a>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <a href="{% url 'vacant_shifts' event.url_name %}" class="nav-link">{% trans "Vacant shifts" %}</a>
                    </li>

                    {% if user_event_view_coordinators %}
                    <li class="nav-item">
                        <a href="{% url 'coordinators' event.url_name %}" class="nav-link">{% trans "All coordinators" %}</a>
                    </li>
                    {% endif %}
                {% endif %}
            </ul>
        </li>

        {% if user_mails_send or user_mails_view %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Mail" %}</p>
            <ul class="nav flex-column">
                {% if user_mails_send and not event.archived %}
                <li class="nav-item">
                    <a href="{% url 'mail:send' event.url_name %}" class="nav-link">{% trans "Send" %}</a>
                </li>
                {% endif %}

                {% if user_mails_view %}
                <li class="nav-item">
                    <a href="{% url 'mail:list' event.url_name %}" class="nav-link">{% trans "All mails" %}</a>
                </li>
                {% endif %}
            </ul>
        </li>
        {% endif %}

        {% if not event.archived and user_statistics_view or event.ask_shirt and user_statistics_specific %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Statistics" %}</p>
            <ul class="nav flex-column">
                {% if not event.archived and user_statistics_view %}
                <li class="nav-item">
                    <a href="{% url 'statistic:overview' event.url_name %}" class="nav-link">{% trans "Overview" %}</a>
                </li>
                {% endif %}

                {% if event.ask_shirt and user_statistics_specific %}
                <li class="nav-item">
                    <a href="{% url 'statistic:shirts' event.url_name %}" class="nav-link">{% trans "T-Shirts" %}</a>
                </li>
                {% endif %}

                {% if not event.archived and event.ask_nutrition and user_statistics_specific %}
                <li class="nav-item">
                    <a href="{% url 'statistic:nutrition' event.url_name %}" class="nav-link">{% trans "Nutrition" %}</a>
                </li>
                {% endif %}
            </ul>
        </li>
        {% endif %}

        {% if event.gifts %}
        {% if user_gifts_edit or user_gifts_view_summary %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Gifts and presence" %}</p>
            <ul class="nav flex-column">
                {% if user_gifts_edit %}
                <li class="nav-item">
                    <a href="{% url 'gifts:list' event.url_name %}" class="nav-link">{% trans "Settings" %}</a>
                </li>
                {% endif %}

                {% if user_gifts_view_summary and not event.archived %}
                    <li class="nav-item">
                        <a href="{% url 'gifts:list_deposit' event.url_name %}" class="nav-link">{% trans "Collected deposit" %}</a>
                    </li>

                    {% if event.ask_shirt %}
                        <li class="nav-item">
                            <a href="{% url 'gifts:list_shirts' event.url_name %}" class="nav-link">{% trans "Missing T-shirts" %}</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
        </li>
        {% endif %}
        {% endif %}

        {% if event.badges %}
        {% if user_badges_edit or user_badges_generate %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Badges" %}</p>
            <ul class="nav flex-column">
                {% if user_badges_edit %}
                <li class="nav-item">
                    <a href="{% url 'badges:settings' event.url_name %}" class="nav-link">{% trans "Settings" %}</a>
                </li>
                {% endif %}

                {% if user_badges_edit_special %}
                <li class="nav-item">
                    <a href="{% url 'badges:list_specialbadges' event.url_name %}" class="nav-link">{% trans "Special badges" %}</a>
                </li>
                {% endif %}

                {% if user_badges_generate and not event.archived %}
                    <li class="nav-item">
                        <a href="{% url 'badges:index' event.url_name %}" class="nav-link">{% trans "Generate" %}</a>
                    </li>

                    {% if event.badge_settings.barcodes %}
                    <li class="nav-item">
                        <a href="{% url 'badges:register' event.url_name %}" class="nav-link">{% trans "Registration" context "Badges" %}</a>
                    </li>
                    {% endif %}
                {% endif %}
            </ul>
        </li>
        {% endif %}
        {% endif %}

        {% if event.prerequisites and user_prerequisites_view %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Prerequisites" %}</p>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a href="{% url 'prerequisites:view_prerequisites' event.url_name %}" class="nav-link">{% trans "Settings and lists" %}</a>
                </li>
            </ul>
        </li>
        {% endif %}

        {% if event.inventory and not event.archived %}
        {% if user_inventory_edit or user_inventory_handle %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Inventory" %}</p>
            <ul class="nav flex-column">
                {% if user_inventory_edit %}
                <li class="nav-item">
                    <a href="{% url 'inventory:event_settings' event.url_name %}" class="nav-link">{% trans "Settings" %}</a>
                </li>
                {% endif %}

                {% if user_inventory_handle %}
                <li class="nav-item">
                    <a href="{% url 'inventory:register' event.url_name %}" class="nav-link">{% trans "Register" context "Register item and badge" %}</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'inventory:take_back' event.url_name %}" class="nav-link">{% trans "Take back" %}</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'inventory:list' event.url_name %}" class="nav-link">{% trans "List" %}</a>
                </li>
                {% endif %}
            </ul>
        </li>
        {% endif %}
        {% endif %}
    </ul>
</nav>
{% endif %}

src/helfertool/templates/helfertool/admin_general_menu.html
{% load i18n globalpermissions inventory toolsettings %}

{% djangosetting "FEATURES_NEWSLETTER" as features_newsletter %}
{% djangosetting "FEATURES_INVENTORY" as features_inventory %}
<nav id="sidemenu">
    <div class="sidemenu-header">{% trans "Settings" %}</div>

    <ul class="nav flex-column">
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "General" %}</p>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a href="{% url "account:view_user" %}" class="nav-link">{% trans "My account" %}</a>
                </li>

                {% if user.is_superuser or user|has_addevent_group %}
                <li class="nav-item">
                    <a href="{% url 'new_event' %}" class="nav-link">{% trans "New event" %}</a>
                </li>
                {% endif %}

                {% if user.is_superuser %}
                <li class="nav-item">
                    <a href="{% url 'adminautomation:event_archive_status' %}" class="nav-link">{% trans "Archiving" %}</a>
                </li>
                {% endif %}

                {% if features_inventory %}
                {% if user.is_superuser or user|is_inventory_admin_any %}
                    <li class="nav-item">
                        <a href="{% url 'inventory:inventory_list' %}" class="nav-link">{% trans "Inventory" %}</a>
                    </li>
                {% endif %}
                {% endif %}

                <li class="nav-item">
                    <a href="{% url "help:create_issue" %}" class="nav-link">{% trans "Support" %}</a>
                </li>
            </ul>
        </li>

        {% if user.is_superuser or user|has_adduser_group %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Users" %}</p>
            <ul class="nav flex-column">
                {% if user.is_superuser or user|has_adduser_group %}
                <li class="nav-item">
                    <a href="{% url 'account:add_user' %}" class="nav-link">{% trans "Add user" %}</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'account:list_users' %}" class="nav-link">{% trans "All users" %}</a>
                </li>
                {% endif %}

                {% if user.is_superuser %}
                <li class="nav-item">
                    <a href="{% url 'account:list_agreements' %}" class="nav-link">{% trans "User agreements" %}</a>
                </li>
                {% endif %}
            </ul>
        </li>
        {% endif %}

        {% if features_newsletter %}
        {% if user.is_superuser or user|has_sendnews_group %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Newsletter" %}</p>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a href="{% url 'news:send' %}" class="nav-link">{% trans "Send news" %}</a>
                </li>

                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'news:remove' %}" class="nav-link">{% trans "Remove recipient" %}</a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'news:failures' %}" class="nav-link">{% trans "Delivery failures" %}</a>
                    </li>
                {% endif %}
            </ul>
        </li>
        {% endif %}
        {% endif %}

        {% if user.is_superuser %}
        <li class="nav-item">
            <p class="sidemenu-section">{% trans "Settings" %}</p>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a href="{% url "toolsettings:templates" %}" class="nav-link">{% trans "Templates" %}</a>
                </li>

                <li class="nav-item">
                    <a href="{% url "toolsettings:check" %}" class="nav-link">{% trans "Check installation" %}</a>
                </li>

                {% if user.is_staff %}
                <li class="nav-item">
                    <a href="{% url 'admin:index' %}" class="nav-link">{% trans "Django Admin Interface" %}</a>
                </li>
                {% endif %}
            </ul>
        </li>
        {% endif %}
    </ul>
</nav>